[package]
name = "magnetic"
description = "Low-latency lock-free queues"
version = "2.0.0"
authors = ["John Shaw <jshaw@shawnation.com>"]
license = "MIT"
repository = "https://github.com/johnshaw/magnetic"
keywords = ["lock-free", "queue"]
documentation = "http://johnshaw.github.io/magnetic/doc/magnetic"

[features]
unstable = []
